name: Prebuild stdenv

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string
      architectures:
        required: true
        type: string
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  prebuild:
    strategy:
      fail-fast: false
      matrix:
        architecture: ${{ fromJson(inputs.architectures) }}
    name: Prebuild ${{ inputs.stage }}-stdenv (${{ matrix.architecture }})
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Binfmt
        uses: docker/setup-qemu-action@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            extra-platforms = ${{ matrix.architecture }}-linux
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 32
      - name: Download Previous Stage
        uses: actions/download-artifact@v4
        with:
          # avoids error if missing
          pattern: ${{ matrix.architecture }}-prebuild-cache
          path: ${{ runner.temp }}/${{ matrix.architecture }}-prebuild-cache
          merge-multiple: true
      - name: Build
        run: |
          urlencode() { printf %s "$1" |sed 's/ /%20/g'; }
          if [ -d '${{ runner.temp }}/${{ matrix.architecture }}-prebuild-cache' ]; then
              NIX_SUBSTITUTERS_ARGS=" \
                  --option require-sigs false \
                  --option trusted-substituters file://$(urlencode '${{ runner.temp }}/${{ matrix.architecture }}-prebuild-cache') \
                  --option substituters file://$(urlencode '${{ runner.temp }}/${{ matrix.architecture }}-prebuild-cache') \
              "
          fi
          echo "$NIX_SUBSTITUTERS_ARGS"
          cp -LR "$(nix build $NIX_SUBSTITUTERS_ARGS .#packages.${{ matrix.architecture }}.${{ inputs.stage }} --print-out-paths)" '${{ matrix.architecture }}-prebuild-cache'
      - name: Upload Current Stage
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.architecture }}-prebuild-cache
          path: ./${{ matrix.architecture }}-prebuild-cache
          overwrite: true
